tests = [
    "capture_tests/CapturedTest.cpp",
    "egl_tests/EGLAndroidFrameBufferTargetTest.cpp",
    "egl_tests/EGLBackwardsCompatibleContextTest.cpp",
    "egl_tests/EGLBufferAgeTest.cpp",
    "egl_tests/EGLChooseConfigTest.cpp",
    "egl_tests/EGLContextASANTest.cpp",
    "egl_tests/EGLContextCompatibilityTest.cpp",
    "egl_tests/EGLContextSharingTest.cpp",
    "egl_tests/EGLCreateContextAttribsTest.cpp",
    "egl_tests/EGLDebugTest.cpp",
    "egl_tests/EGLDisplaySelectionTest.cpp",
    "egl_tests/EGLDisplayTest.cpp",
    "egl_tests/EGLLockSurface3Test.cpp",
    "egl_tests/EGLMemoryUsageReportTest.cpp",
    "egl_tests/EGLNoConfigContextTest.cpp",
    "egl_tests/EGLNoErrorTest.cpp",
    "egl_tests/EGLPreRotationTest.cpp",
    "egl_tests/EGLPrintEGLinfoTest.cpp",
    "egl_tests/EGLProgramCacheControlTest.cpp",
    "egl_tests/EGLProtectedContentTest.cpp",
    "egl_tests/EGLQueryContextTest.cpp",
    "egl_tests/EGLReadinessCheckTest.cpp",
    "egl_tests/EGLRecordableTest.cpp",
    "egl_tests/EGLRobustnessTest.cpp",
    "egl_tests/EGLSurfaceTest.cpp",
    "egl_tests/EGLSurfacelessContextTest.cpp",
    "egl_tests/EGLSyncTest.cpp",
    "gl_tests/ActiveTextureCacheTest.cpp",
    "gl_tests/AdvancedBlendTest.cpp",
    "gl_tests/AtomicCounterBufferTest.cpp",
    "gl_tests/AttributeLayoutTest.cpp",
    "gl_tests/BPTCCompressedTextureTest.cpp",
    "gl_tests/BindGeneratesResourceTest.cpp",
    "gl_tests/BindUniformLocationTest.cpp",
    "gl_tests/BlendFuncExtendedTest.cpp",
    "gl_tests/BlendIntegerTest.cpp",
    "gl_tests/BlendMinMaxTest.cpp",
    "gl_tests/BlendPackedTest.cpp",
    "gl_tests/BlitFramebufferANGLETest.cpp",
    "gl_tests/BlobCacheTest.cpp",
    "gl_tests/BufferDataTest.cpp",
    "gl_tests/BuiltinVariableTest.cpp",
    "gl_tests/ClearTest.cpp",
    "gl_tests/ClientArraysTest.cpp",
    "gl_tests/ClipControlTest.cpp",
    "gl_tests/ClipDistanceTest.cpp",
    "gl_tests/ColorMaskTest.cpp",
    "gl_tests/CompressedTextureFormatsTest.cpp",
    "gl_tests/ComputeShaderTest.cpp",
    "gl_tests/ContextLostTest.cpp",
    "gl_tests/ContextNoErrorTest.cpp",
    "gl_tests/CopyCompressedTextureTest.cpp",
    "gl_tests/CopyTexImageTest.cpp",
    "gl_tests/CopyTexture3DTest.cpp",
    "gl_tests/CopyTextureTest.cpp",
    "gl_tests/CubeMapTextureTest.cpp",
    "gl_tests/DXT1CompressedTextureTest.cpp",
    "gl_tests/DXTSRGBCompressedTextureTest.cpp",
    "gl_tests/DebugMarkerTest.cpp",
    "gl_tests/DebugTest.cpp",
    "gl_tests/DepthStencilFormatsTest.cpp",
    "gl_tests/DepthStencilTest.cpp",
    "gl_tests/DepthWriteTest.cpp",
    "gl_tests/DifferentStencilMasksTest.cpp",
    "gl_tests/DiscardFramebufferEXTTest.cpp",
    "gl_tests/DrawBaseVertexBaseInstanceTest.cpp",
    "gl_tests/DrawBaseVertexVariantsTest.cpp",
    "gl_tests/DrawBuffersTest.cpp",
    "gl_tests/DrawElementsIndirectTest.cpp",
    "gl_tests/DrawElementsTest.cpp",
    "gl_tests/DrawRangeElementsTest.cpp",
    "gl_tests/EGLImageMECFriendlyTest.cpp",
    "gl_tests/ETCTextureTest.cpp",
    "gl_tests/ExternalBufferTest.cpp",
    "gl_tests/ExternalWrapTest.cpp",
    "gl_tests/FenceSyncTests.cpp",
    "gl_tests/FloatingPointSurfaceTest.cpp",
    "gl_tests/FragDepthTest.cpp",
    "gl_tests/FramebufferFetchTest.cpp",
    "gl_tests/FramebufferMixedSamplesTest.cpp",
    "gl_tests/FramebufferMultiviewTest.cpp",
    "gl_tests/FramebufferRenderMipmapTest.cpp",
    "gl_tests/FramebufferTest.cpp",
    "gl_tests/GLSLTest.cpp",
    "gl_tests/GLSLUBTest.cpp",
    "gl_tests/GeometryShaderTest.cpp",
]

stop_at = "GeometryShaderTest.cpp"

excluded = []

for path in tests:
    name = path.split("/")[-1].replace(".cpp", "")
    excluded.append(f"-{name}.*")
    if path.endswith(stop_at):
        break

print("--gtest_filter=" + ":".join(excluded))